name: order_food
description: A monorepo for Flutter and Python projects
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  # Add your project dependencies here

dev_dependencies:
  melos: ^3.0.0

